### ISSUE TITLE
Allow moving DQMH modules in virtual folders

### ISSUE THREAD

**Issue by Oberloewe** [PantherLAB/PantherDashboard#28]
I use several DQMH modules in my project, and to keep things organized, I created virtual subfolders where I move all the automatically generated DQMH stuff that I don't actually need that often. The auto-generated VIs are not moved on the disk.

The native DQMH tools still seem to work with the "virtual" folder structure of the DQMH VIs.

Suggested improvement:
Extend the project parsing to the way the native DQMH tools scan the project.

![DQMH virutal folder](https://user-images.githubusercontent.com/76879693/220841986-91553fc5-dc4c-4eb2-bde3-1c9da38bb96d.png)

**Comment by enoearias** [comment]
Hi @Oberloewe, the structure of the DQMH module libraries is something that should not be changed because it can interfere with DQMH scripting. I strongly recommend you not to change the structure of your modules in order to have a more pleasant experience.

As for Panther Dashboard, the intention is to help manage DQMH modules and help users follow the best practices, that's why this feature will not be implemented.

I really appreciate you taking the time to write and request new features, please feel free to do so again if you find another feature you want to see in Panther Dashboard.

Thank you.
Enrique.

**Comment by enoearias** [comment]
Hi @Oberloewe I just found a post on the NI Forums talking about this topic, please read @dnattinger sugestion.
[Internal file Organization in a Module?](https://forums.ni.com/t5/DQMH-Consortium-Toolkits/Internal-file-organization-in-a-module/m-p/4283998#M2470)

**Comment by Oberloewe** [comment]
Hi Enrique,

thank you for the link.
I already shared my experiences to this topic.

regards Thomas

Am Di., 7. März 2023 um 01:52 Uhr schrieb Enrique Noe Arias <
***@***.***>:
